### ISSUE TITLE
READMEを書いておいてほしいです

### ISSUE THREAD

**Issue by shibatadaiki** [itok01/todo-rails#1]
要件にはなかったのですが、作成した機能と画面がざっとわかるREADMEを書いておいてほしいです！（ITトレーニングのREADME（https://github.com/super-studio/it_training/blob/master/textbooks/day18_middle_problem.md）を参考に書いて貰う形で構いません）

**Comment by itok01** [comment]
こちら `README.md` を作成いたしました！

**Comment by shibatadaiki** [comment]
確認しました！OKです！
