### ISSUE TITLE
タスク内容は詳細、一覧画面でも編集画面の見た目と同じようになるように行変えしてほしいです

### ISSUE THREAD

**Issue by shibatadaiki** [itok01/todo-rails#10]
要件外の見栄えの問題ではありますが
![スクリーンショット 2021-02-04 6 59 16](https://user-images.githubusercontent.com/25131575/106816918-6f773b80-66b9-11eb-9134-2d1e817eddaf.png)
![スクリーンショット 2021-02-04 6 59 25](https://user-images.githubusercontent.com/25131575/106816924-730ac280-66b9-11eb-9f31-1c4f8b75ce63.png)
![スクリーンショット 2021-02-04 6 59 37](https://user-images.githubusercontent.com/25131575/106816926-7605b300-66b9-11eb-86a4-f6a1356041df.png)

**Comment by itok01** [comment]
こちら https://github.com/itok01/todo-rails/commit/f03703c45682ce5e499e411786d0f186dab716c2 にて修正しました！
