### ISSUE TITLE
URL直打ちすると他ユーザーの編集画面やアサイン画面に行けてしまうので修正してほしいです

### ISSUE THREAD

**Issue by shibatadaiki** [itok01/todo-rails#11]
こういうところの想定が抜けるとセキュリティインシデントなどにつながるので注意です！
![スクリーンショット 2021-02-04 7 52 50](https://user-images.githubusercontent.com/25131575/106820086-1f4ea800-66be-11eb-9cec-f000955e65d1.png)
![スクリーンショット 2021-02-04 7 52 57](https://user-images.githubusercontent.com/25131575/106820091-21186b80-66be-11eb-966c-35b878bbc6ec.png)
![スクリーンショット 2021-02-04 7 53 08](https://user-images.githubusercontent.com/25131575/106820094-22499880-66be-11eb-81ff-7ff83b6d6c25.png)

**Comment by itok01** [comment]
こちら https://github.com/itok01/todo-rails/commit/ef79d0b3574856113ff438467f9be5f82b595a83 にて修正しました！

**Comment by shibatadaiki** [comment]
OKです！
