### ISSUE TITLE
Railsが自動生成してしまうファイルで、使用していないものは消しておいてほしいです

### ISSUE THREAD

**Issue by shibatadaiki** [itok01/todo-rails#2]
https://github.com/itok01/todo-rails/blob/main/app/helpers/tasks_helper.rb
や
https://github.com/itok01/todo-rails/blob/main/app/assets/javascripts/tasks.coffee
などの、rails gのコマンドで使用するファイルと一緒に作成されるもので、使用していないものがあるのはあまり良くないのでこれらは消しておいてください

ちなみにご存知かもですが、下記事のような設定で自動生成されるファイルの制限もできます
https://qiita.com/ko-suke24/items/993d0b8313e66fd800df

**Comment by itok01** [comment]
こちら不要なファイルを削除しました！
また、ファイル生成の config については知らなかったです。ありがとうございます！

**Comment by shibatadaiki** [comment]
OKです！良かったです
