### ISSUE TITLE
ec_forceの場合、private配下のメソッドのインデントはつけてないので、認識だけお願いします

### ISSUE THREAD

**Issue by shibatadaiki** [itok01/todo-rails#3]
private配下のメソッドのインデントをつけるかつけないかに絶対的な正解はない（らしい）ので修正の必要はないのですが、ec_forceの場合、private配下のメソッドのインデントはつけてないので、そこの認識だけお願いします！
https://qiita.com/jnchito/items/b1f093b83643cef522ef

**Comment by itok01** [comment]
こちら https://github.com/itok01/todo-rails/commit/bba2f19bd5af5bffc51ad85f0eb74852ab03c98a にて修正しました！
また、インデントのルールについて承知しました。
