### ISSUE TITLE
未ログインユーザーが他のユーザーが作成したタスク詳細に入れないバグの修正をお願いします

### ISSUE THREAD

**Issue by shibatadaiki** [itok01/todo-rails#4]
上記タイトルのバグの修正をお願いします！
ご質問があれば聞いてください！

<img width="1423" alt="スクリーンショット 2021-02-04 6 08 41" src="https://user-images.githubusercontent.com/25131575/106809792-7305c500-66af-11eb-9c5e-a02fb005b190.png">

<img width="1128" alt="スクリーンショット 2021-02-04 6 06 16" src="https://user-images.githubusercontent.com/25131575/106809729-5d909b00-66af-11eb-947f-65eb558daa82.png">

**Comment by itok01** [comment]
ありがとうございます！
こちら https://github.com/itok01/todo-rails/commit/47afd3bbda795d6cda8a91bcb85cef3b13dd8ea7 にて修正しました！
