### ISSUE TITLE
（発表までに間に合いそうであれば）編集画面や削除ポップアップ、エラーメッセージなどに英語が混じっているのでできる限り日本語に統一しておいてほしいです

### ISSUE THREAD

**Issue by shibatadaiki** [itok01/todo-rails#7]
![スクリーンショット 2021-02-04 6 11 09](https://user-images.githubusercontent.com/25131575/106812489-1c01ef00-66b3-11eb-89d4-d6fa0bc312c8.png)

<img width="521" alt="スクリーンショット 2021-02-04 6 46 37" src="https://user-images.githubusercontent.com/25131575/106813818-db0ada00-66b4-11eb-93c6-73a06c5cbc14.png">

![スクリーンショット 2021-02-04 7 13 26](https://user-images.githubusercontent.com/25131575/106816730-22936500-66b9-11eb-8f6e-574f46329b4d.png)

**Comment by itok01** [comment]
こちら https://github.com/itok01/todo-rails/commit/b943ad0c12973cf458a64e98eed481015d5092cc https://github.com/itok01/todo-rails/commit/740049d06b92ca72f214f3191f596e2d7d44a10e にて修正しました！
