### ISSUE TITLE
「気に入りません」の文言を直してほしいです

### ISSUE THREAD

**Issue by shibatadaiki** [itok01/todo-rails#8]
要件通りなので伊藝さん何も悪くないんですが個人的に「気に入りません」の日本語訳がどうしても気になってしまうので、、「削除されてしまうのは悲しいことです」とかの意味が通る文章にしておいてほしいです笑

![スクリーンショット 2021-02-04 6 12 14](https://user-images.githubusercontent.com/25131575/106813031-d42f9780-66b3-11eb-83d3-e2c241b82ec9.png)

**Comment by itok01** [comment]
確かに自分もおかしいと思っていました笑
こちら https://github.com/itok01/todo-rails/commit/07bc0ac63f5775e643e7051e903d92a3606efe48 にて修正しました！
