### ISSUE TITLE
（発表までに間に合いそうであれば）tasks.jsonを叩いたときにエラーになるので直してほしいです

### ISSUE THREAD

**Issue by shibatadaiki** [itok01/todo-rails#9]
API対応を自主的にやられていて素晴らしいですね！
showアクションなどは問題なく値が返ってきますがindexアクションでjsonリクエストするとエラーになってしまうのでこちら直せたら直しておいてください。
（これは要件外なので今日中に修正できそうであれば着手するという形で構いません）
![スクリーンショット 2021-02-04 7 09 40](https://user-images.githubusercontent.com/25131575/106816523-d9dbac00-66b8-11eb-8870-777c781e0b14.png)

ちなみに全然余談ですがjbuilderを始めとするRailsのデフォルトJson生成機能はよく遅さが問題になるのでいろいろな代替案が検討されてたりします
（ecforceは普通にjbuilderですが）
https://qiita.com/ttiger55/items/d144b8094d61b70955bf
https://shrkw.hatenablog.com/entry/2020/07/16/123000

**Comment by itok01** [comment]
JSON API については生成されたものをそのままにしていました笑
JSON Serializer についての記事の共有ありがとうございます！
調べると様々な JSON Serializer があり、 Jbuilder 以外を使うとなると選定が難しそうですね 👀
こちら https://github.com/itok01/todo-rails/commit/a9f70563842b6287e05aac8d31e3af0f4d4d8a85 にて修正しました！

**Comment by shibatadaiki** [comment]
あ、デフォだったんですね笑
（コメントついてるから想定してたのかと思っちゃいました）

OKです！
